{{- if and .Values.server.enabled .Values.server.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.labels.app }}-svc
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}  # Common labels
spec:
  ports:
    - name: http
      port: {{ .Values.server.service.port }}
      protocol: TCP
      targetPort: {{ .Values.server.service.targetPort }}
  selector:
    app: {{ .Values.labels.app }}
  type: {{ .Values.server.service.type }}
  sessionAffinity: None
{{- end }}
