// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ph/v1/monitors": {
            "get": {
                "description": "Get all active monitor rules",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "monitor"
                ],
                "summary": "List monitor rules",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_cylonchau_pantheon_pkg_model.MonitorRule"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_cylonchau_pantheon_pkg_api_query.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "Add a new monitor rule",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "monitor"
                ],
                "summary": "Create monitor rule",
                "parameters": [
                    {
                        "description": "Monitor Rule configuration",
                        "name": "rule",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_cylonchau_pantheon_pkg_api_monitor.MonitorRuleReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_cylonchau_pantheon_pkg_api_query.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_cylonchau_pantheon_pkg_api_query.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_cylonchau_pantheon_pkg_api_query.Response"
                        }
                    }
                }
            }
        },
        "/ph/v1/monitors/{id}": {
            "post": {
                "description": "Modify an existing monitor rule",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "monitor"
                ],
                "summary": "Update monitor rule",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Monitor Rule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Monitor Rule configuration",
                        "name": "rule",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_cylonchau_pantheon_pkg_api_monitor.MonitorRuleReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_cylonchau_pantheon_pkg_api_query.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_cylonchau_pantheon_pkg_api_query.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_cylonchau_pantheon_pkg_api_query.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove a monitor rule by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "monitor"
                ],
                "summary": "Delete monitor rule",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Monitor Rule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_cylonchau_pantheon_pkg_api_query.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_cylonchau_pantheon_pkg_api_query.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_cylonchau_pantheon_pkg_api_query.Response"
                        }
                    }
                }
            }
        },
        "/ph/v1/proxy": {
            "get": {
                "description": "This endpoint proxies requests to another server.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Proxy"
                ],
                "summary": "Reverse Proxy",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Protocol (http/https)",
                        "name": "schema",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Host to proxy to",
                        "name": "host",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Port to proxy to",
                        "name": "port",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Basic auth credentials",
                        "name": "base",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Bearer token for authentication",
                        "name": "bearer",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Additional parameter 1",
                        "name": "param1",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Additional parameter 2",
                        "name": "param2",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/ph/v1/selectors": {
            "get": {
                "description": "List selectors",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Selectors"
                ],
                "summary": "List selectors",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "post": {
                "description": "Update selector by old key and value",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Selectors"
                ],
                "summary": "Update selector",
                "parameters": [
                    {
                        "description": "Update Selector Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_cylonchau_pantheon_pkg_api_query.QueryEditSelector"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_cylonchau_pantheon_pkg_api_query.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_cylonchau_pantheon_pkg_api_query.Response"
                        }
                    }
                }
            }
        },
        "/ph/v1/targets": {
            "put": {
                "description": "Create prometheus target.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Targets"
                ],
                "summary": "Create prometheus target.",
                "parameters": [
                    {
                        "description": "body",
                        "name": "query",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/github_com_cylonchau_pantheon_pkg_api_target.Target"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/ph/v1/targets/clean": {
            "delete": {
                "description": "Remove all targets where is_del = 1.",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "tags": [
                    "Targets"
                ],
                "summary": "Clean all targets marked as deleted.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/ph/v1/targets/cmd/{key}/{value}": {
            "get": {
                "description": "List target with instance labels",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Targets"
                ],
                "summary": "List target with instance labels",
                "parameters": [
                    {
                        "type": "string",
                        "description": "label key name",
                        "name": "key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "label value name",
                        "name": "value",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/ph/v1/targets/selector/{key}/{value}": {
            "get": {
                "description": "List target with instance labels",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Targets"
                ],
                "summary": "List target with instance labels",
                "parameters": [
                    {
                        "type": "string",
                        "description": "selector key name",
                        "name": "key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "selector value name",
                        "name": "value",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/ph/v1/targets/{id}": {
            "get": {
                "description": "Retrieve a target using its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Targets"
                ],
                "summary": "Get a target by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Target ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_cylonchau_pantheon_pkg_model.TargetRaw"
                        }
                    }
                }
            },
            "post": {
                "description": "Update prometheus instance target id with provided parameters.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Targets"
                ],
                "summary": "Update prometheus target with target id.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "target id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Target update information",
                        "name": "target",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_cylonchau_pantheon_pkg_api_target.TargetChg"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove prometheus target target id.",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "tags": [
                    "Targets"
                ],
                "summary": "Remove prometheus target with target id.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "target id",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/ph/v2/targets/selector/{key}/{value}": {
            "get": {
                "description": "List target with instance labels",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Targets"
                ],
                "summary": "List target with instance labels",
                "parameters": [
                    {
                        "type": "string",
                        "description": "selector key name",
                        "name": "key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "selector value name",
                        "name": "value",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_cylonchau_pantheon_pkg_api_meta_v1.TypeMeta": {
            "type": "object",
            "properties": {
                "kind": {
                    "type": "string"
                }
            }
        },
        "github_com_cylonchau_pantheon_pkg_api_monitor.MonitorRuleReq": {
            "type": "object",
            "required": [
                "name",
                "namespace",
                "port_name",
                "selector",
                "type"
            ],
            "properties": {
                "drop_metrics": {
                    "description": "Optional regex to drop metrics",
                    "type": "string"
                },
                "labels": {
                    "description": "Comma-separated: env=prod,owner=sre (optional)",
                    "type": "string"
                },
                "metric_path": {
                    "description": "e.g. /metrics (optional, defaults to /metrics)",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "port_name": {
                    "type": "string"
                },
                "selector": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "pod",
                        "service"
                    ]
                }
            }
        },
        "github_com_cylonchau_pantheon_pkg_api_query.QueryEditSelector": {
            "type": "object",
            "required": [
                "new_key",
                "new_value",
                "old_key",
                "old_value"
            ],
            "properties": {
                "new_key": {
                    "description": "新键",
                    "type": "string"
                },
                "new_value": {
                    "description": "新值",
                    "type": "string"
                },
                "old_key": {
                    "description": "源键",
                    "type": "string"
                },
                "old_value": {
                    "description": "源值",
                    "type": "string"
                }
            }
        },
        "github_com_cylonchau_pantheon_pkg_api_query.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        },
        "github_com_cylonchau_pantheon_pkg_api_target.Target": {
            "type": "object",
            "required": [
                "selectors"
            ],
            "properties": {
                "addresses": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "kind": {
                    "$ref": "#/definitions/github_com_cylonchau_pantheon_pkg_api_meta_v1.TypeMeta"
                },
                "selectors": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "targets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_cylonchau_pantheon_pkg_api_target.TargetItem"
                    }
                }
            }
        },
        "github_com_cylonchau_pantheon_pkg_api_target.TargetAuth": {
            "type": "object",
            "properties": {
                "base": {
                    "type": "string"
                },
                "bearer_token": {
                    "type": "string"
                }
            }
        },
        "github_com_cylonchau_pantheon_pkg_api_target.TargetChg": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "auth": {
                    "$ref": "#/definitions/github_com_cylonchau_pantheon_pkg_api_target.TargetAuth"
                },
                "metric_path": {
                    "type": "string"
                },
                "scrape_time": {
                    "type": "integer"
                },
                "scrape_timeout": {
                    "type": "integer"
                }
            }
        },
        "github_com_cylonchau_pantheon_pkg_api_target.TargetItem": {
            "type": "object",
            "required": [
                "address"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "auth": {
                    "$ref": "#/definitions/github_com_cylonchau_pantheon_pkg_api_target.TargetAuth"
                },
                "labels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "metric_path": {
                    "type": "string"
                },
                "params": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "scrape_time": {
                    "type": "integer"
                },
                "scrape_timeout": {
                    "type": "integer"
                }
            }
        },
        "github_com_cylonchau_pantheon_pkg_model.MonitorRule": {
            "type": "object",
            "properties": {
                "drop_metrics": {
                    "description": "Regex to drop metrics",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "labels": {
                    "description": "Labels to inject: k1=v1,k2=v2",
                    "type": "string"
                },
                "metric_path": {
                    "description": "e.g. /metrics",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "description": "K8s namespace",
                    "type": "string"
                },
                "port_name": {
                    "description": "Target port name or port number",
                    "type": "string"
                },
                "selector": {
                    "description": "Comma-separated app=portal,env=prod",
                    "type": "string"
                },
                "type": {
                    "description": "\"pod\" or \"service\"",
                    "type": "string"
                }
            }
        },
        "github_com_cylonchau_pantheon_pkg_model.TargetRaw": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "base_auth": {
                    "type": "string"
                },
                "bearer_token": {
                    "type": "string"
                },
                "metric_path": {
                    "type": "string"
                },
                "schema": {
                    "type": "string"
                },
                "scrape_time": {
                    "type": "integer"
                },
                "scrape_timeout": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "v0.0.0-dev",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Pantheon server",
	Description:      "Prometheus hub, distrubed prometheus targent manager.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
